version: '3'

services:
  mydb:
    build: ./mysqld
    container_name: bxMysqld
    env_file:
      - .bitrix.env
    user: "1000"
    volumes:
      - ./var/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql

  redis:
    build: ./redis
    container_name: bxRedis
    volumes:
      - ./logs/redis:/var/log/redis

  memcached:
    image: memcached
    container_name: mc
    restart: always

  httpd:
    build: ./php
    container_name: bxHttpd
    volumes:
      - ./var/www:/var/www/html
      - ./logs/httpd:/var/log/httpd
      - ./logs/php:/var/log/php
    env_file:
      - .bitrix.env
    depends_on:
      - mydb

  push:
    build: ./push
    container_name: bxPush
    env_file:
      - .bitrix.env
    volumes:
      - ./logs/push-server:/var/log/push-server
    depends_on:
      - redis
    restart: always

  nginx:
    build: ./nginx
    container_name: bxNginx
    ports:
      - '80:80'
    volumes:
      - ./var/www:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - httpd
      - push
      - mydb
      - redis

